### ISSUE TITLE
Make the team membership public

### ISSUE THREAD

**Issue by gautamkrishnar** [RITct/RITct-discussions#1]
Guys, Please make your RITct Membership public.
We are planning something like this:
https://blog.justinwflory.com/2016/10/set-up-github-organizations-clubs/

As mentioned in the blog:
If someone is in your organization, make sure you encourage them to show it off! By default, GitHub sets the team member visibility to private. Unless a member of the organization sets themselves as public, they won’t appear as a part of the organization to visitors.

Publicizing your membership is an underestimated step in bringing new contributors in. It’s even helpful for older members too. By publicizing memberships, you are giving faces and real people to characterize your organization. If someone finds your organization in a search or in a link, it looks better to have rows of people associated with the group. The alternative of a team with what looks like no members implies your club is inactive. It can also make your club look smaller than it is. Additionally, individual team members also get to show off your organization on their individual profiles. This is helpful for anyone visiting their profile for activities or programming experience. For university students, this is helpful for applying for co-ops or internships.

To make a membership visible, the organization member has to go to the “People” page of the organization. On the page, next to their name, there is an option for “Public” or “Private” in a drop-down menu. Change it to “Public”.

People page: https://github.com/orgs/RITct/people

![img](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fi.jwf.io%2Fu%2F6631b7d25bbbdfa9033a2d922912fddd.png)

Mention: @RITct/team

**Comment by ParadoxZero** [comment]
Closing an issue will archive it. Considering its an active discussion, let is stay open.

**Comment by gautamkrishnar** [comment]
@RITct/team Just a friendly reminder to all....
Guys, Please make your RITct Membership public.
We are planning something like this:
https://blog.justinwflory.com/2016/10/set-up-github-organizations-clubs/

As mentioned in the blog:
If someone is in your organization, make sure you encourage them to show it off! By default, GitHub sets the team member visibility to private. Unless a member of the organization sets themselves as public, they won’t appear as a part of the organization to visitors.

Publicizing your membership is an underestimated step in bringing new contributors in. It’s even helpful for older members too. By publicizing memberships, you are giving faces and real people to characterize your organization. If someone finds your organization in a search or in a link, it looks better to have rows of people associated with the group. The alternative of a team with what looks like no members implies your club is inactive. It can also make your club look smaller than it is. Additionally, individual team members also get to show off your organization on their individual profiles. This is helpful for anyone visiting their profile for activities or programming experience. For university students, this is helpful for applying for co-ops or internships.

To make a membership visible, the organization member has to go to the “People” page of the organization. On the page, next to their name, there is an option for “Public” or “Private” in a drop-down menu. Change it to “Public”.

People page: https://github.com/orgs/RITct/people

![img](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fi.jwf.io%2Fu%2F6631b7d25bbbdfa9033a2d922912fddd.png)

**Comment by ParadoxZero** [comment]
@RITct/team reminder. Please make membership public.
