### ISSUE TITLE
Improve RIT's Wikipedia page

### ISSUE THREAD

**Issue by jophab** [RITct/RITct-discussions#10]
Hey guys,
Anybody interested in improving our wikipedia page?
Add some good images and contents.
Refer other colleges wiki for examples.

https://en.wikipedia.org/wiki/Rajiv_Gandhi_Institute_of_Technology,_Kottayam

**Comment by Poirot1729** [comment]
Okay, I'll look into it. :+1:

**Comment by Poirot1729** [comment]
Will they allow students to be admins?

**Comment by jophab** [comment]
@Poirot1729 I don't think so. We cant have a official page managed by students. Especially because of student politics. 
But we can have unofficial pages.

**Comment by gautamkrishnar** [comment]
Yes I agree with @jophab...  AFAIK there are multiple pages for our college now... none of them are official...

**Comment by gautamkrishnar** [comment]
We must contact these page admins so that we can merge these pages:
https://www.facebook.com/ritkottayam/?ref=br_rs
https://www.facebook.com/GRITKottayam/?ref=br_rs
https://www.facebook.com/Govt-Rajiv-Gandhi-institute-of-technology-Kottayam-195524257154888/?ref=br_rs

**Comment by Poirot1729** [comment]
Making pages is easy, I don't think we will be able to maintain it. We hardly had anyone volunteer for our TH page. If we don't post regularly it will die off and will join the above list one day.
