### ISSUE TITLE
Merge RIT Facebook pages

### ISSUE THREAD

**Issue by gautamkrishnar** [RITct/RITct-discussions#11]
Currently, there are multiple facebook pages for our college. None of them are official. 

We must contact these page admins so that we can merge these pages: 
https://www.facebook.com/ritkottayam/?ref=br_rs 
https://www.facebook.com/GRITKottayam/?ref=br_rs 
https://www.facebook.com/Govt-Rajiv-Gandhi-institute-of-technology-Kottayam-195524257154888/?ref=br_rs

@RITct/team  Can someone volunteer and update the status here?

We can get the merged page verified by the Facebook if possible.

PS: As a government college, I think our social media presence is not at all important. But it we can use that page to share our college's official updates. It must be managed by the faculties. I think Ashokan sir would be the best choice for the faculty admin.

**Comment by gautamkrishnar** [comment]
No one is interested :smile: Closing...

**Comment by ParadoxZero** [comment]
No one as in the page admins?

**Comment by gautamkrishnar** [comment]
Nope No one to volunteer... :smile:

**Comment by MrGrayCode** [comment]
I'm sorry. I have a fake FB account and contacting people with that would be creepy, that's why I did not volunteer.

**Comment by ParadoxZero** [comment]
Let it stay open. I will try when I get free.
