### ISSUE TITLE
Online coding lessons

### ISSUE THREAD

**Issue by gautamkrishnar** [RITct/RITct-discussions#12]
I just found a new platform called replit classroom which we can teach students coding. You can simply create assignments for the students so that they can join the classroom and learn while submitting the assignments. We can coding lessons for freshers. **Please share your thoughts!**

Link: https://repl.it/site/classrooms

We can even create a separate repository with the list of the classrooms created by the tinkerhub RIT community.

Just created an organization named RIT Creative team...  **Make sure that you select it while joining as a teacher.**  
Here's an example: https://repl.it/classroom/invite/GyqbG9D

CC: @RITct/team

**Comment by MrGrayCode** [comment]
Created a classroom for C++, will start with the lessons once the freshers join :+1:

**Comment by Aksh77** [comment]
@gautamkrishnar Greatl idea !

**Comment by gautamkrishnar** [comment]
@aksh77 you must start the biopython classes soon :smile:
