### ISSUE TITLE
StudentMail Benefits

### ISSUE THREAD

**Issue by UKnowWhoIm** [RITct/RITct-discussions#15]
Me and @abhinavk001 created an [API](https://github.com/UKnowWhoIm/student-mail-benefits) to store the details of student benefits. 

Was thinking about encouraging people here to contribute. What would be better, forking the repo here or transferring ownership to RITct @gautamkrishnar

**Comment by UKnowWhoIm** [comment]
Currently the database is empty, will add some entries tomorrow

**Comment by gautamkrishnar** [comment]
@UKnowWhoIm it's your choice @UKnowWhoIm. Happy to see that finally, someone is working on it 😄
