### ISSUE TITLE
Building a bot for RIT

### ISSUE THREAD

**Issue by GopikrishnanSasikumar** [RITct/RITct-discussions#6]
Lets build a bot which will talk about:

1. Our college.
2. Basic info like how to reach, contact ..etc
3. Technological and cultural programs and clubs we have.
4. Latest news about RIT.

**Comment by shashank-sj** [comment]
Add me #6

**Comment by Abhi1401** [comment]
Why bot ? Who's going to use it ? :\ :|

**Comment by Abhi1401** [comment]
Instead we can work on our website collaboratively. 

[RITCT_Website](https://github.com/RITct/RITCT_Website)
[ritct.github.io](https://github.com/RITct/ritct.github.io)

There are many who don't clearly know the workflow of git.
Such a project would be good for them to understand this platform. But problem is not much of current members visit github frequently.

**Comment by ParadoxZero** [comment]
I second that working on smaller things first is better. Just set up a repository and start.

**Comment by Poirot1729** [comment]
We can do that bot project if we have RITU this year, but otherwise it's good to start with something simple to get used to github like @Abhi1401 said. Also we'll have freshers coming in next sem, it would be good if we set up a website and hopefully make them contribute.

**Comment by ParadoxZero** [comment]
Make a getting started website for RITct.
You can work on the bot once the website is finished.

**Comment by GopikrishnanSasikumar** [comment]
Well this is a project created for learning machine learning. Bots are useful in many ways and it is getting popular. Lets do the bot after the website.

**Comment by ParadoxZero** [comment]
Or do it in parallel and attach to RITct website. There are 18 people watching that repository, I am sure 18 people can't work on a project that small. 😓

**Comment by GopikrishnanSasikumar** [comment]
@ParadoxZero thats a great Idea. Let the people interested in machine learning do the bot, others do the website and finally we can merge them together.

**Comment by ParadoxZero** [comment]
But like I said, plan things first. And plan quickly.

Form a team for the bot project. Don't go more than 5-6 (even that's too much IMO)

Then start discussing. particular features of the project and how to do it.

**Comment by GopikrishnanSasikumar** [comment]
ok,people interested in working on bot comment here. I will ping you

**Comment by gautamkrishnar** [comment]
We can split into 2 teams and work on both projects. I think its better.
Tip: @GopikrishnanSasikumar please dont assign people to an issue, its better to mention them using their username
