### ISSUE TITLE
How to write a good project wiki?

### ISSUE THREAD

**Issue by ParadoxZero** [RITct/RITct-discussions#9]
When developing larger projects. It's important to maintain a proper documentation.

Project wiki's are a good way to do that.

The problem is, how to write a good wiki?

What all should be the included? How to write a proper documentation?

**Comment by gautamkrishnar** [comment]
https://readthedocs.org/ is a great platform to host the documentation. It is extensively used by most of the open source communities like @DuckDuckGo, @Mozilla etc. GitHub wiki is also a simple alternative. Please check out http://www.writethedocs.org/ to know more about how to write a good documentation.

## What 's a good doc?
I think a good documentation must include:
* Project's concise **description**
* List of **project's dependencies**.
* Project's **Installation/Setup instructions**.
* Projects **use cases** if it is a library it must have all the API references and examples. If the project is an application, we must include as much screenshot and videos as possible. Using .gif is also a good idea.
* Project's **Contribution Guidelines/Coding Conventions** for new contributors. It must also include clear instructions for new contributors to get started with the project. It must also include a project's to-do list.
* If the project is a group project, it must include names of all the **core contributors** (**optional**, but required to encourage more people to contribute)
* Project's **license** info (required, for legal purposes)
* **Contact info** of the maintainer.
